#tag::mn[]
micronaut:
    application:
        name: config # <1>
    server:
        port: 8082 # <2>
#end::mn[]
#tag::consul[]
consul:
  client:
    registration:
      enabled: true
      # Alters the retry count
      retry-count: 10
      # Alters fail fast behaviour
      fail-fast: false
    defaultZone: "${CONSUL_HOST:consul}:${CONSUL_PORT:8500}"
#end::consul[]
endpoints:
  health:
    enabled: true
    sensitive: false