version: "3"
services:
  consul:
    image: consul
    ports:
    - "8500:8500"
  config:
    image: ms.config
    ports:
    - "8082:8082"
    depends_on:
    - "consul"
  injector:
    image: ms.injector
    ports:
    - "8081:8081"
    depends_on:
    - "consul"